var background=chrome.extension.getBackgroundPage(),featureArticleSupport={ar:!0,bar:!1,bg:!1,cs:!0,da:!0,de:!0,el:!0,en:!0,es:!0,fa:!1,fr:!0,it:!0,lt:!1,he:!0,hr:!1,hu:!0,ksh:!1,ru:!1,sv:!0,tr:!1,nds:!1,nl:!0,nn:!1,no:!1,pl:!0,pt:!0,sr:!1,fi:!1,zh:!0,ja:!0,ko:!0,vi:!0,uk:!0};function startup(){setTimeout(loadwiki,100)}
function loadwiki(){if(!background.wikihistory||background.wikihistory.length==0){var a=document.getElementById("loadingpage");if(localStorage.showFeatureArticle=="true")a=background.getCurrentLang(),a=featureArticleSupport[a]?"http://"+a+".m.wikipedia.org":"http://en.m.wikipedia.org";else{a.src="./welcome.html";return}}else{if(background.currentHistoryPosition>=background.wikihistory.length)background.currentHistoryPosition=background.wikihistory.length-1;a=background.wikihistory[background.currentHistoryPosition].url}displayURL(a)}
function displayURL(a){if(background.wikicache[a])background.wikicache[a]=background.wikicache[a].replace(/<body style=['"].*?['"]/ig,"<body style='width:"+(parseInt(localStorage.pageWidth)-20)+"px' "),document.open(),document.write(background.wikicache[a]),document.close(),document.body.style.width=parseInt(localStorage.pageWidth)-20+"px",jQuery(document).triggerHandler("ready"),document.onmouseup=function(a){createRightClickPopupBox(a)};else{var b=a.match(/^http:\/\/(.*?).m/)[1],d=new XMLHttpRequest;
d.open("GET",a,!0);d.onreadystatechange=function(){if(d.readyState==4){var c=d.responseText;if(c!="")c=c.replace(/<link(.*?)href=(['"])(\/.*?)(['"])/ig,"<link$1href=$2http:$3$4").replace(/\bsrc=(['"])(\/\/.*?)(['"])/ig,"src=$1https:$2$3").replace(/\bsrc=(['"])(\/.*?)(['"])/ig,"src=$1https://"+b+".m.wikipedia.org$2$3").replace("</head>","<link rel='stylesheet' href='custom.css'></head>").replace("<div class='message notice'>","<div style='display:none;' 'message notice'>").replace("<div id='searchbox'",
"<div style='display:none;' id='searchbox'").replace("id='footmenu'>","id='footmenu' style='display:none'>").replace(/<div class='mwm-message/ig,"<div style='display: none' class='mwm-message").replace("<body","<body style='width:"+(parseInt(localStorage.pageWidth)-20)+"px' ")+'<script type="text/javascript" src="post-load.js"><\/script>',localStorage.currentPage=a,background.wikicache[a]=c,document.open(),document.write(c),document.close(),console.log("complete loading")}};d.send()}}
function modifyPageAfterLoad(){document.onmouseup=function(a){createRightClickPopupBox(a)};localStorage.fontSize?document.getElementsByTagName("html")[0].style.fontSize=localStorage.fontSize+"em":document.getElementsByTagName("html")[0].style.fontSize="0.8em"}var selectedText="";
function createRightClickPopupBox(a){(b=document.getElementById("rightClickPopupBox"))&&b.parentNode.removeChild(b);if(a.button==2&&(selectedText=window.getSelection().toString(),selectedText!="")){var b=document.createElement("div");b.setAttribute("style","position: absolute; cursor: pointer; background-color: white; -webkit-box-shadow: 1px 1px 7px black;top: "+(a.y+window.pageYOffset)+"px; left: "+a.x+"px;");b.id="rightClickPopupBox";b.innerHTML='<div id="rightClickPopupBoxSearch" style="margin: 5px">Search for "'+
selectedText.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")+'"</div>';document.getElementsByTagName("body")[0].appendChild(b);if(parseInt(b.style.left)+b.clientWidth>=document.width)b.style.left=parseInt(b.style.left)-b.clientWidth+"px";document.getElementById("rightClickPopupBoxSearch").onmouseover=function(){document.getElementById("rightClickPopupBox").style.backgroundColor="#ffb"};document.getElementById("rightClickPopupBoxSearch").onmouseout=function(){document.getElementById("rightClickPopupBox").style.backgroundColor=
"white"};document.getElementById("rightClickPopupBoxSearch").onmouseup=function(a){if(selectedText!="")a.preventDefault(),a.stopPropagation(),parent.document.getElementById("searchbox").value=selectedText,parent.doSearch(),document.getElementById("rightClickPopupBox").parentNode.removeChild(b)}}}window.onload=function(){setTimeout(loadwiki,100)};
